### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by burtbeckwith**

### CODE REVIEW

**Comment by getwasim** [comment]
Burt can I use this plugin for my application which is in Grails 1.3.7 when the plugin is upgraded after the merge.

**Comment by burtbeckwith** [comment]
As I said in the commit comments, it's currrently set to a minimum of 2.2 but you can change that if you want. The plugin project has to use Grails 2+ for development and releasing, but you can target any Grails version range you want as long as the code works in all supported versions. I used @CompileStatic in at least one class and that requires Grails 2.2 or higher since that's the first version that used Groovy 2.0+ which added support for static typing. If you want to drop the minimum version to 1.3.7 you'll just need to remove all @CompileStatic annotations, and otherwise you should be fine.

**Comment by getwasim** [comment]
Oh! Thanks Burt will make the required changes. Thanks again in helping me in creating and publishing my first plugin.

**Comment by getwasim** [comment]
Also, Burt I have seen that you have removed the CustomStringFunction and moved the metaclass methods to  CustomStringGrailsPlugin.groovy. What if I add more methods in future. Will I add all of them in the CustomStringGrailsPlugin class.

**Comment by burtbeckwith** [comment]
That's up to you. If the plugin class starts to get cluttered you could move that code into its own class and call it from doWithDynamicMethods, or leave it where it is. Both are correct and it just depends on your code style/preferences.

**Comment by getwasim** [comment]
Okay Thanks.. I have made changes according to your comments and resubmitted it on grails.org but the plugin is still pending approval. Is there something which I am missing to get the plugin approved.

**Comment by getwasim** [comment]
Burt I have refactored/optimized the code more and replaced switch cases with direct addressing Array. Please review them and approve the plugin.

**Pull request merged**
